### ISSUE TITLE
OIS segfaults with Adaptive Bramich method

### ISSUE THREAD

**Issue by RuiyangWangW** [toros-astro/ois#21]
```python
ois.optimal_system(image=hdul.data, refimage=template, method="AdaptiveBramich", poly_degree=2)
```
exits with a segmentation fault when `poly_degree` is not equal to 0.

We found that this is possibly because `bkg_dof` is overflowing in `src/oistools.c:build_matrix_system`.
 
We run several different poly_degrees, and the `bkg_dof` is constantly equal to `-INT_MAX`.
gdb frame files are attached.
[ois2.gdb.txt](https://github.com/toros-astro/ois/files/4167930/ois2.gdb.txt)
[oispoly_degree3.gdb.txt](https://github.com/toros-astro/ois/files/4167931/oispoly_degree3.gdb.txt)
[ois.gdb.txt](https://github.com/toros-astro/ois/files/4167933/ois.gdb.txt)

**Comment by martinberoiz** [comment]
Merged.
